In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[1:5]= 100
arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [7]:
arr = np.arange(0,11)

In [8]:
slice_of_arr = arr[0:6]


In [9]:
slice_of_arr[:]
slice_of_arr[:]=99
slice_of_arr

arr




array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [10]:
a

NameError: name 'a' is not defined

In [11]:
arr_copy = arr.copy()

In [12]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [13]:
arr_copy [:]= 100

In [14]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [15]:
arr_2d= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [28]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr_2d[0,2]

3

In [19]:
arr_2d[1,2]

6

In [18]:
arr_2d[:1,1:]

array([[2, 3]])

In [20]:
arr_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
arr_2d[,:2]

SyntaxError: invalid syntax (<ipython-input-21-e42d650b8b86>, line 1)

In [22]:
arr_2d>5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [30]:
arr = np.arange(10)

In [31]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr<5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [40]:
bool_arr =arr<5

In [41]:
arr[bool_arr]

array([0, 1, 2, 3, 4])

In [ ]:
arr_2d