In [3]:
my_list = [1,2,3]

In [4]:
my_list
import numpy as np


In [5]:
arr = np.array(my_list)

In [6]:
my_mat= [[1,2,3],[4,5,7],[7,8,4],[1,4,6],[3,9,2]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 7],
       [7, 8, 4],
       [1, 4, 6],
       [3, 9, 2]])

In [7]:
np.arange(1,10,3)

array([1, 4, 7])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [28]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [18]:
np.random.rand(2)

array([0.70387185, 0.42673938])

In [19]:
np.random.randn(2)

array([ 0.41920574, -0.78882937])

In [29]:
np.random.randint(1,15,4)

array([ 8, 12, 11,  5])

In [30]:
arr= np.arange(8)

In [31]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [50]:
arr=arr.reshape(2,4)

In [42]:
ranarr = np.random.randint(1,50,10)

In [43]:
ranarr

array([35,  9, 13, 38, 31, 19, 13,  7, 23,  7])

In [44]:
ranarr

array([35,  9, 13, 38, 31, 19, 13,  7, 23,  7])

In [45]:
ranarr.max()

38

In [46]:
ranarr.min()

7

In [47]:
ranarr.argmax()

3

In [51]:
arr.shape

(2, 4)

In [52]:
from numpy.random import randint

In [56]:
randint(1,20)

10